# Generated by Django 4.2.4 on 2023-08-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_add_genericsettings_and_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericsettings",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
