# Generated by Django 4.2.4 on 2023-08-22 16:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("base", "0019_genericsettings_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "columns",
                    wagtail.fields.StreamField(
                        [
                            (
                                "column",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "content_type",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("text", "Text"),
                                                    ("list", "List"),
                                                ]
                                            ),
                                        ),
                                        ("content", wagtail.blocks.RichTextBlock()),
                                    ],
                                    label="Column",
                                    max_num=4,
                                    min_num=1,
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer",
            },
            bases=("wagtailcore.page",),
        ),
    ]
