# Generated by Django 4.2.4 on 2023-08-22 16:23

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_footersettings_delete_footer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footersettings",
            name="columns",
            field=wagtail.fields.StreamField(
                [
                    (
                        "column",
                        wagtail.blocks.StructBlock(
                            [], label="Footer Columns", max_num=4, min_num=1
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
