# Generated by Django 4.2.4 on 2023-08-22 16:32

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_alter_footersettings_columns"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footersettings",
            name="columns",
        ),
        migrations.AddField(
            model_name="footersettings",
            name="rows",
            field=wagtail.fields.StreamField(
                [
                    (
                        "row",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "content",
                                                    wagtail.blocks.RichTextBlock(),
                                                )
                                            ],
                                            label="Item",
                                        )
                                    ),
                                )
                            ],
                            label="Row",
                            min_num=1,
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
